In [1]:
import numpy as np

In [8]:
np.eye(2)
i4=np.eye(4)
i4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.savetxt("eye.txt",i4)  #savefile

In [12]:
np.loadtxt("eye.txt")   #loadfile

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
c,v=np.loadtxt("data.csv",delimiter=',',usecols=(6,7),unpack=True) 

In [36]:
print(c,"===",v)

336.1 === 21144800.0


In [32]:
np.array?

In [33]:
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 'uintp', 'P', 'long', 'l', 7, 'L', 8, 'longlong', 'q', 9, 'ulonglong', 'Q', 10, 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'uint32', 'Int32', 'UInt32', 'i4', 'u4', 'int64', 'uint64', 'Int64', 'UInt64', 'i8', 'u8', 'int16', 'uint16', 'Int16', 'UInt16', 'i2', 'u2', 'int8', 'uint8', 'Int8', 'UInt8', 'i1', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 'float_', 

In [39]:
vwap=np.average(c,weights=v)
print("VWAP=",vwap)


VWAP= 336.1


In [54]:
h,l=np.loadtxt("prices.csv",delimiter=",",usecols=(4,5),unpack=True)
print("highest value=",max(h))
print("lowest value=",min(l))
print("Spread high price=",np.ptp(h))  #ptp() is a function which takes array as an input
print("Spread low price=",np.ptp(l))   # and return the difference b/w the highest and lowest values

highest value= 699.569977
lowest value= 90.699997
Spread high price= 610.099976
Spread low price= 614.370026


In [109]:
c=np.loadtxt("data.csv",delimiter=",",usecols=(6))

In [ ]:
import numpy as np
c=np.arange(50, dtype=float)
print("median =", np.median(c))
sorted = np.msort(c)
print("sorted =", sorted)
N = len(c)
print(N)
print("middle =", sorted[int((N - 1)/2)])
print("average middle =", np.average)
print("variance =", np.var(c))
print("variance from definition =", np.mean((x - x.mean())**2))

In [125]:
c=np.arange(20)
print("Mean=",np.mean(c))
print("Median=",np.median(c))
print("sorted value=",np.msort(c))
print("variance=",np.var(c))
print("standard deviation=",np.std(c))
print("log=",np.log(c))
print("log=",np.log10(c))

Mean= 9.5
Median= 9.5
sorted value= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
variance= 33.25
standard deviation= 5.766281297335398
log= [      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527
 2.48490665 2.56494936 2.63905733 2.7080502  2.77258872 2.83321334
 2.89037176 2.94443898]
log= [      -inf 0.         0.30103    0.47712125 0.60205999 0.69897
 0.77815125 0.84509804 0.90308999 0.95424251 1.         1.04139269
 1.07918125 1.11394335 1.14612804 1.17609126 1.20411998 1.23044892
 1.25527251 1.2787536 ]


c:\users\khawaja_osama\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys
c:\users\khawaja_osama\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in log10
  


In [141]:
c=np.array(np.arange(2,17))


In [142]:
print(c)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [143]:
np.diff(c)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [144]:
c[:-1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [153]:
b=np.diff(c)/c[:-1]   #taking inverse ;)

In [148]:
c=np.array([2,5,3,6,7,4,9,6,3,5,5,3])
print(np.where(c>4))                 #where is a function through which returns index nos of the applied condition

(array([ 1,  3,  4,  6,  7,  9, 10], dtype=int32),)


In [149]:
np.sqrt?


In [154]:
b

array([ 1.5       , -0.4       ,  1.        ,  0.16666667, -0.42857143,
        1.25      , -0.33333333, -0.5       ,  0.66666667,  0.        ,
       -0.4       ])

In [158]:
ratio=np.std(b)/np.mean(b)
annual_volatility=ratio/np.sqrt(1/252)
annual_volatility

49.287601658982936

In [161]:
c=np.arange(0,150,3)
print(np.diff(c)/c[:-1])
print("Standard deviation=",np.std(c))
log_returns=np.diff(np.log(c))

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909
 0.08333333 0.07692308 0.07142857 0.06666667 0.0625     0.05882353
 0.05555556 0.05263158 0.05       0.04761905 0.04545455 0.04347826
 0.04166667 0.04       0.03846154 0.03703704 0.03571429 0.03448276
 0.03333333 0.03225806 0.03125    0.03030303 0.02941176 0.02857143
 0.02777778 0.02702703 0.02631579 0.02564103 0.025      0.02439024
 0.02380952 0.02325581 0.02272727 0.02222222 0.02173913 0.0212766
 0.02083333]
Standard deviation= 43.292609068985435


c:\users\khawaja_osama\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [167]:
c

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147])

In [164]:
np.where(c<30)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32),)

In [166]:
np.take(c,np.where(c<30))


array([[ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27]])

In [20]:
import datetime
#def dates2num(s):
    return (datetime.datetime.strptime(s,"%d-%m-%Y").date())#.strftime("%d-%m-%Y")

In [21]:
dates2num('28-01-2011')

datetime.date(2011, 1, 28)

In [104]:
import datetime
def dates2num_2(s):
    return datetime.datetime.strptime(str(s),"%d-%m-%Y").date().weekday()

In [105]:
dates2num_2('28-01-2011')

4

In [106]:
import numpy as np

In [146]:
dates, price, close=np.loadtxt('prices.csv', delimiter=',', usecols=(0,2,3), converters={1: dates2num_2}, unpack=True, dtype='str')
dates=list(map(dates2num_2, dates))
dates=np.asanyarray(dates,'float64')
dates

array([0., 1., 2., ..., 2., 3., 4.])

In [154]:
price=np.asanyarray(price,'f')
price

array([213.43   , 214.59999, 214.37999, ..., 117.52   , 116.45   ,
       116.65   ], dtype=float32)

In [155]:
zeros=np.zeros(5,dtype='float')
zeros

array([0., 0., 0., 0., 0.])

In [163]:
close=np.asanyarray(price,'d')
close

array([213.42999268, 214.59999084, 214.37998962, ..., 117.51999664,
       116.44999695, 116.65000153])

In [165]:
for i in range(5):
    indices=np.where(dates==i)
    prices=np.take(close,indices)
    avg=np.mean(prices)
    days=['Monday','Tuesday','Wednesday','Thursday','Friday']
    print('Day=',days[i],' Price=',prices,' Average=',avg)
    zeros[i]=avg

Day= Monday  Price= [[213.42999268 212.80000305 202.50999451 192.36999512 195.69000244
  202.33999634 205.75       220.00999451 225.38000488 220.47000122
  232.99998474 234.98001099 242.19998169 247.02999878 271.88000488
  263.83999634 250.25       254.70001221 247.27999878 258.29000854
  255.96000671 277.68997192 266.93002319 258.52999878 249.88000488
  260.         260.44000244 261.48001099 247.58000183 251.79000854
  240.76000977 265.82000732 276.07998657 293.98001099 281.6000061
  294.73999023 318.47000122 309.09002686 302.22000122 317.20001221
  308.46002197 306.67999268 315.5        318.64001465 324.36999512
  321.6000061  322.8500061  325.64001465 338.82998657 326.86999512
  335.79998779 347.88998413 356.79000854 351.23999023 361.3999939
  353.17999268 335.99002075 353.1499939  344.30999756 334.05999756
  326.09997559 350.33999634 349.73999023 347.86001587 339.19998169
  329.97000122 345.70001221 327.20001221 317.36001587 327.58999634
  356.34002686 365.42999268 390.3500061  397

In [166]:
zeros

array([311.19360592, 311.53395003, 312.14347943, 315.10943713,
       315.32999876])

In [170]:
top = np.max(zeros)
print("Highest average", top)
print("Top day of the week", np.argmax(zeros))
bottom = np.min(zeros)
print("Lowest average", bottom)
print("Bottom day of the week", np.argmin(zeros))

Highest average 315.3299987620065
Top day of the week 4
Lowest average 311.1936059200402
Bottom day of the week 0


In [171]:
local=np.datetime64('2018-01-31')
with_offset=local=np.datetime64('2018-01-01')

local-with_offset

numpy.timedelta64(0,'D')

In [ ]:
import requests
import datetime as dt
import matplotlib.pyplot as plt
def crypto_crncy_price(symbol, comparison_symbol = 'USD', all_data=True, aggregate=1,limit = 1, exchange=''):
    a = int(input('1 for Minute\n2 for Hourly\n3 for Today '))
    url = 'https://min-api.cryptocompare.com/data/histominute?fsym={}&tsym={}&limit={}&aggregate={}'.format(symbol.upper(), comparison_symbol.upper(), limit, aggregate)
    if a == 1: url = url.replace('&limit=1', '&limit=9999')
    elif a == 2: url = url.replace('histominute','histohour'); url = url.replace('&limit=1', '&limit=9999')
    elif a == 3: url = url.replace('histominute','histoday')
    if all_data and a == 3: url += '&allData=true'
    if exchange: url += '&e={}'.format(exchange)
    a = requests.get(url).json()['Data']
    b = [(a[i]['time'], a[i]['close'], dt.datetime.fromtimestamp(a[i]['time'])) for i in range(len(a))]
    plt.plot([i[2] for i in b], [i[1] for i in b])
    plt.xticks(rotation = 30)
    plt.show()

# function testing: 
a = print(crypto_crncy_price('btc'))
b = print(crypto_crncy_price('eth'))
c = print(crypto_crncy_price('neo'))
d = print(crypto_crncy_price('neo', 'pkr'))
for i in a,b,c,d: print(i)