In [7]:
import numpy as np

In [16]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [34]:
a[:,::2,1]

array([[ 1,  9],
       [13, 21]])

In [20]:
a[0,1,3]

7

In [21]:
a[:,1,1] # first argument give the range of matrix, 2nd arg gives the row ,3rd arg give column

array([ 5, 17])

In [23]:
a[0,1,1:3]

array([5, 6])

In [30]:
(a[1,0:2,1]).reshape(2,1,1)

array([[[13]],

       [[17]]])

In [31]:
a[:,0:5,0:2] #excluding 2 elements from 2 matrix  3 row 3&4 col

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]])

In [32]:
a[1,1,::2]

array([16, 18])

In [33]:
a[1,2,::3]

array([20, 23])

In [37]:
a.ravel()
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [40]:
a.shape=(6,4)  # resize and reshape are same , both are in memory
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
a.resize(2,4,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])